-- require("core.plugin_config.gruvbox")
require("core.plugin_config.catpuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.lsp_config")
-- require("core.plugin_config.todo-comments")
require("core.plugin_config.comments")
require("core.plugin_config.illuminate")
require("core.plugin_config.mini-indentscope")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.conform")
require("core.plugin_config.codesnap")
require("core.plugin_config.obsidian")
require("core.plugin_config.zenmode")
